### ISSUE TITLE
missing urwid dependency?

### ISSUE THREAD

**Issue by dpinol** [TomasTomecek/sen#128]
In OSX, with python 3.6 and pip 9.0.1, it failed to automatically install the urwid dependency.

```
sudo pip3 install sen
Password:
executing pip with sudo, you may want sudo's -H flag.
Collecting sen
  Downloading sen-0.5.1-py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 658kB/s
Collecting urwidtrees (from sen)
  Downloading urwidtrees-1.0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-14um8ooa/urwidtrees/setup.py", line 4, in <module>
        import urwidtrees.version as v
      File "/private/tmp/pip-build-14um8ooa/urwidtrees/urwidtrees/__init__.py", line 6, in <module>
        from .decoration import DecoratedTree, CollapsibleTree
      File "/private/tmp/pip-build-14um8ooa/urwidtrees/urwidtrees/decoration.py", line 4, in <module>
        import urwid
    ModuleNotFoundError: No module named 'urwid'
```
After manually installing urwid, it worked fine

**Comment by TomasTomecek** [comment]
This issue comes from urwidtrees, what you are seeing is combination of these issues: https://github.com/pazz/urwidtrees/issues/28 https://github.com/pazz/urwidtrees/issues/24 https://github.com/pazz/urwidtrees/issues/35

Unfortunately I wasn't able to resolve this (so `$ pip3 install sen` works) -- the solution is to install `urwid` explicitly before installing sen. I proposed patch to document this, can you take a look? #128

**Comment by dpinol** [comment]
hi, thanks! I guess you meant #129 instead of #128 in your last commit

**Comment by TomasTomecek** [comment]
Yes, #129, my bad.

**Comment by dpinol** [comment]
dealt by #129. Thank you @TomasTomecek

**Comment by darkn3rd** [comment]
Thanks.  ` pip3 install urwid` is a workaround.
