### ISSUE TITLE
Problem with setting up on OSX

### ISSUE THREAD

**Issue by pwielgolaski** [TomasTomecek/sen#63]
I tried to run it on OSX, but command from documentation does not work on my machine
I mean version with running sen in docker.

So I tried to use just http connectivity like this, it works but it is quite verbose
```
docker run -ti --rm -e TERM=$TERM -e DOCKER_HOST=$DOCKER_HOST -e DOCKER_CERT_PATH=$DOCKER_CERT_PATH -e DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY -v $DOCKER_CERT_PATH:$DOCKER_CERT_PATH tomastomecek/sen
```
Later  I noticed that guys from https://github.com/crosbymichael/dockerui are using different file location after I change line to this it also worked.
```
docker run --privileged -v /var/run/docker.sock:/run/docker.sock -ti -e TERM=$TERM tomastomecek/sen
```

Is there problem with documentation or file can be in different place ...

**Comment by TomasTomecek** [comment]
Thanks for trying out sen! A couple notes:

1. I am not using OS X so I have no idea how docker works there
2. there already were 2 PRs submitted by @ne0zen #42 #44 regarding running sen on OS X


If I understand this correctly, the issue is that docker socket on your machine is at `/var/run/docker.sock` and not `/run/docker.sock`.

If that's the case, I can definitely improve the docs.

Thanks for reporting the issue and sorry for the inconvenience.

**Comment by pwielgolaski** [comment]
It seems that it is default location for docker.sock https://docs.docker.com/v1.8/articles/basics/#bind-docker-to-another-host-port-or-a-unix-socket
So maybe you could take a look if you dont have it on this location as well.

It would be good you update docs to point to default location.

**Comment by TomasTomecek** [comment]
will do, @pwielgolaski thanks for report!
